<?php

namespace Kate\Helper;

require_once dirname(__FILE__) . '/../../../../libs/Kate/Helper/Translator.php';

/**
 * Test class for Translator.
 * Generated by PHPUnit on 2012-03-23 at 19:04:18.
 */
class TranslatorTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Translator
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
	$this->object = new Translator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * Generated from @assert ('Ahoj', 1, 2) == 'Hello'.
     *
     * @covers Kate\Helper\Translator::googleTranslate
     */
    public function testGoogleTranslate() {
	$this->assertEquals(
		'Hello'
		, Kate\Helper\Translator::googleTranslate('Ahoj', 1, 2)
	);
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGet().
     */
    public function testGet() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testTranslate().
     */
    public function testTranslate() {
	// Remove the following lines when you implement this test.
	$this->markTestIncomplete(
		'This test has not been implemented yet.'
	);
    }

}

?>
